Currency formatter (rounding, commas, and trimming insignificant 0's)
ArkEcosystemArchive/explorer pull request #25
Opened 2017-10-19 21:20 UTC by krau612

Created a pipe to format currencies based on whether the selected currency is crypto (8 decimal places) or fiat (2 decimal places). It also strips 0's from the end of a number (ex. 123.50000000 -> 123.5). By default it uses the selected currency, but it can be overridden with an optional argument (for values that are always in one specific currency like in the header).

Resolves #9

2017-11-07 11:03 UTC, luciorubeens requested changes

2017-11-07 11:03 UTC, luciorubeens commented on src/app/pages/address/address.component.html
> +                    <a href="#" (click)="goToAddress($event, item.address)" *ngIf="i < votersNumber">{{item.address}} ({{(item.balance / 100000000) | currencyFormat: 'ARK'}} ARK)</a>
Need to use a variable to handle this, because we can't manually change it to DEVNET.. the same discussed in #18

2017-11-30 19:07 UTC, boldninja commented
@krau612 how is this looking?

2017-11-30 20:28 UTC, krau612 commented
@boldninja Hey sorry for taking so long to get back to this, school and trying to get a job have taken up all of my time.

I've gone ahead and made the changes, but I couldn't test them because of some issue with res.ticker not being defined. That issue doesn't seem to be limited to this branch though.

2017-12-28 12:39 UTC, faustbrian commented
@krau612 Could you resolve the conflicts? Will take a look then and merge or let you know what should be changed.

2018-01-12 11:48 UTC, faustbrian commented
Will close this for now as there are quite a few conflicts, if you still wish to add this feature freel free to send a new PR.

2018-01-12 11:48 UTC, closed without merging