chore: replace tslint for eslint
ArkEcosystemArchive/explorer pull request #833
Opened 2020-01-23 09:51 UTC by Highjhacker

## Summary

Replace `tslint` for `eslint`

Resolve #829 

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

- Not sure about the rules, do we want more than these ?
- Tests were excluded from tslint.json previously, but I included them this time, can remove if not necessary.
- Put it in --no-fix in package.json for now since wasn't sure about the rules we want to apply.

2020-01-25 18:02 UTC, ItsANameToo commented
you didn't apply the merge properly @Highjhacker

2020-01-27 15:54 UTC, ItsANameToo requested changes
can you run `yarn lint` and see what errors it runs into? then check for the errors whether they are relevant or if the rule should be disabled

2020-01-27 15:54 UTC, ItsANameToo commented on .eslintignore
> +/node_modules/**
please keep the coverage line too in case someone ran it locally and the coverage folder was generated

2020-01-27 15:54 UTC, ItsANameToo commented on package.json
> +    "lint": "vue-cli-service lint --no-fix \"./*.{ts,js,json,md,vue}\" \"./src/**/*.{ts,js,json,md,vue}\" \"./__tests__/**/*.{ts,js,json,md,vue}\"",
re-add `prettier` to the `lint` command as it's now unused. Also make sure eslint fixes the errors that it can

2020-01-31 12:32 UTC, Highjhacker commented
Better but still linting issues, such as : 

```js
importMultiPaymentTransactions from '@/components/tables/MultiPaymentTransactions.vue';
```
```js
mport CryptoCompareService from '@/services/crypto-compare';
```
```js
export default classstBlocks extends Vue {
```

Also with the spread operator `...` where sometimes it changes it to `..`

2020-02-05 14:17 UTC, ItsANameToo commented
when I run this, it still shows a few warnings / errors 🤔

2020-02-05 14:24 UTC, ItsANameToo requested changes

2020-02-05 14:24 UTC, ItsANameToo commented on .prettierrc.json
> +  "printWidth": 80,
better to set this to 120 again, 80 is quite small

2020-02-05 14:24 UTC, ItsANameToo commented on .eslintrc.js
> +    "no-console": process.env.NODE_ENV === "production" ? "error" : "off",
I rather not have those production checks, as that will result in issues when people don't lint it with the right `NODE_ENV`

2020-02-05 14:24 UTC, ItsANameToo commented on src/App.vue
> +      'bg-theme-page-background text-theme-text-content min-h-screen font-sans xl:pt-8'
can you check about a rule to not remove these commas?

2020-02-05 14:30 UTC, ItsANameToo commented
Can you also add a lint step to the github workflow so we catch any linting issues in case people skip the step? [desktop wallet has one](https://github.com/ArkEcosystem/desktop-wallet/blob/develop/.github/workflows/test.yml) and OC too which also includes committing any fixes

2020-02-06 20:35 UTC, ItsANameToo approved these changes

2020-02-06 20:35 UTC, merged